# Generated by `python -m util.export_plover_plugin` from src/expressionmodel.py -- do not edit by hand.
"""
The rule model of the expression abbreviation layer: what the composer, the decoder and the Plover plugin share
(stdlib only; `src.expressions` re-exports these names). The `*`/`#` selector keys and the position names live
here, `src.affixes` and `src.ambiguitychecker` import them.
"""

from __future__ import annotations

from dataclasses import dataclass

from .strokes import Strokes

__all__ = ["PREFIX", "SUFFIX", "STAR_KEY", "HASH_KEY", "RESERVED_MARK_KEYS", "AttachRule", "BriefRule", "Rules"]

PREFIX = "prefix"
SUFFIX = "suffix"

# Physical realization on the Starboard: `*` = key 10, `#` = key 15 (see src/ambiguitychecker.py).
STAR_KEY = 10
HASH_KEY = 15
RESERVED_MARK_KEYS = (STAR_KEY, HASH_KEY)  # the */# variant selectors (Q2)


@dataclass(frozen=True)
class AttachRule:
    expression: tuple[str, ...]       # particle word-units, contiguous
    position: str                     # src.affixes.PREFIX or SUFFIX
    keypress: tuple[int, ...]         # kappa; */# selector keys included
    family: str = ""                  # Q2 learnable unit; variants share it
    elision: str = ""                 # "base" | "elided": one chord for the pair, host decides (src/elision.py)

    def __post_init__(self) -> None:
        if not self.expression:
            raise ValueError("attach rule needs a non-empty expression")
        if self.position not in (PREFIX, SUFFIX):
            raise ValueError(f"attach rule position must be {PREFIX!r} or {SUFFIX!r}")
        if not self.keypress:
            raise ValueError("attach rule needs a non-empty keypress")


@dataclass(frozen=True)
class BriefRule:
    expression: tuple[str, ...]
    strokes: Strokes                  # beta; usually one stroke (Q8 allows more)
    family: str = ""

    def __post_init__(self) -> None:
        if not self.expression:
            raise ValueError("brief rule needs a non-empty expression")
        if not self.strokes:
            raise ValueError("brief rule needs at least one stroke")


@dataclass(frozen=True)
class Rules:
    briefs: tuple[BriefRule, ...] = ()
    attaches: tuple[AttachRule, ...] = ()
    # Ordered pairs (first expression, second expression) of adjacent attaches
    # that may NOT both attach: the union of two attach keypresses is
    # commutative, so `ce que` and `que ce` would write the same chord. The
    # second particle of a banned pair is left as a content token (the first
    # attaches onto its longform stroke). See `orderBan` in src/expressionrules.py.
    orderBan: frozenset[tuple[tuple[str, ...], tuple[str, ...]]] = frozenset()

    def __post_init__(self) -> None:
        for rule in self.briefs + self.attaches:
            if not all(isinstance(unit, str) and unit for unit in rule.expression):
                raise ValueError("rule expressions are non-empty word-unit strings")
