# Generated by `python -m util.export_plover_plugin` from src/keyconflicts.py -- do not edit by hand.
"""
Which keys of one stroke cannot be pressed together, as a footprint (user decision 2026-10-04).

On the Starboard each pinky owns a square of four keys (right 22-25, left 0-3). The finger can press
a single key, an adjacent pair (an edge of the square) or all four, but never a diagonal pair, and
never three: a diagonal needs the other two keys down as well. Every other finger accepts any
combination of its own keys (checked against `Starboard._possibleKeypress`).

So a key conflicts with itself AND with its diagonal partner: `expand(keys)` is the keys plus their
partners ("as if the diagonal were pressed too"). Two key sets can share a stroke exactly when
`expand(a)` and `b` are disjoint. That is the same test as `SimContext.isLegal` on the union for
every combination of two sets of keys (the one difference: all four pinky keys together stay
legal but count as a conflict, which never matters because a host holding all four takes no
other pinky key anyway; `src/test/keyconflicts_test.py` checks the equivalence by brute force),
and it makes the strict overlap test of the expression layer legality-aware: attaches or families
that cannot stack because two of their keys sit on a pinky diagonal are caught as overlapping.

The partner map is DERIVED from the layout (a pair of keys of one finger that is not a legal
keypress), not hard-coded.
"""

from __future__ import annotations

from collections.abc import Iterable


class KeyConflicts:
    def __init__(self, partners: dict[int, frozenset[int]] | None = None) -> None:
        self.partners: dict[int, frozenset[int]] = dict(partners or {})
        self._partnerMask = {k: sum(1 << p for p in ps) for k, ps in self.partners.items()}

    @classmethod
    def fromStarboard(cls, starboard: object) -> "KeyConflicts":
        """Partners = key pairs of one finger that are not a legal keypress."""
        table = getattr(starboard, "_possibleKeypress", None)
        partners: dict[int, set[int]] = {}
        if table is not None:
            for finger in table.fingers:
                combos = table[finger]
                keys = sorted(c[0] for c in combos if len(c) == 1)
                for i, a in enumerate(keys):
                    for b in keys[i + 1:]:
                        if (a, b) not in combos:
                            partners.setdefault(a, set()).add(b)
                            partners.setdefault(b, set()).add(a)
        return cls({k: frozenset(v) for k, v in partners.items()})

    def expand(self, keys: Iterable[int]) -> frozenset[int]:
        """The keys plus every diagonal partner."""
        out = set(keys)
        for k in list(out):
            out |= self.partners.get(k, frozenset())
        return frozenset(out)

    def conflict(self, a: Iterable[int], b: Iterable[int]) -> bool:
        """True when the two key sets cannot be pressed in one stroke (shared key or diagonal)."""
        return bool(self.expand(a) & frozenset(b))

    def conflictCount(self, a: Iterable[int], b: Iterable[int]) -> int:
        """How many keys of `b` collide with `a` (equal, or the diagonal partner of one of `a`)."""
        return len(self.expand(a) & frozenset(b))

    def expandMask(self, mask: int) -> int:
        """`expand` on a key bitmask."""
        out = mask
        m = mask
        while m:
            low = m & -m
            out |= self._partnerMask.get(low.bit_length() - 1, 0)
            m ^= low
        return out
